[build]
  publish = "creative_agency2"   # Arahkan ke folder creative_agency2 sebagai root

[[redirects]]
  from = "/about"
  to = "/inner_page/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/inner_page/contact.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/inner_page/portfolio-gallery.html"
  status = 200
